version: "3.0"

networks:
  system:
    driver: bridge

services:
  bank:
    build: bank
    container_name: bank
    networks:
      - system
    ports:
      - "8080:8080"
    volumes:
      - ./data/ca.pem:/ca.pem
    environment:
      - CLIENT_ID=buc3b1hhuc714r78env0
      - CLIENT_SECRET=PBV7q0akoP603rZbU0EFdxbhZ-djxF7FIVwyKaLnBYU
      - TOKEN_URL=https://authorization.cloudentity.com:8443/default/system/oauth2/token
      - TIMEOUT=5s
      - ROOT_CA=/ca.pem

  acp:
    container_name: acp
    image: docker.artifactory.syntegrity.com/authorization:latest
    networks:
      system:
        aliases:
          - authorization.cloudentity.com
    ports:
     - 8443:8443
    restart: on-failure
    volumes:
      - ./data/seed.yaml:/seed.yaml
    command:
     - server
     - start
     - --sql.url
     - postgres://user:password@postgres/authorization?sslmode=disable
     - --hazelcast.address
     - hazelcast:5701
     - --secret.key
     - KNEcLGdDqpwrXDubqPgDSUkMMsLPXaHh
     - --server.cert.path
     - /certs/srv/cert.pem
     - --server.key.path
     - /certs/srv/cert-key.pem
     - --demo
     - --dev

  postgres:
    image: postgres:12.4
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - system
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=authorization

  hazelcast:
    container_name: hazelcast
    image: hazelcast/hazelcast:3.12
    networks:
      - system
    ports:
      - 5701:5701
