version: "3.0"

networks:
  system:
    driver: bridge

services:
  tpp:
    build:
      context: .
      dockerfile: tpp/Dockerfile
    container_name: tpp
    networks:
      - system
    ports:
      - "8090:8090"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/tpp_cert.pem:/tpp_cert.pem
      - ./data/tpp_key.pem:/tpp_key.pem
    environment:
      - CLIENT_ID=bugkgm23g9kregtu051g
      - ISSUER_URL=https://authorization.cloudentity.com:8443/default/openbanking
      - REDIRECT_URL=http://localhost:8090/callback
      - CERT_FILE=/tpp_cert.pem
      - KEY_FILE=/tpp_key.pem
      - ROOT_CA=/ca.pem

  consent-page:
    build:
      context: .
      dockerfile: consent-page/Dockerfile
    container_name: consent-page
    networks:
      - system
    ports:
      - "8080:8080"
    volumes:
      - ./data/ca.pem:/ca.pem
    environment:
      - CLIENT_ID=buc3b1hhuc714r78env0
      - CLIENT_SECRET=PBV7q0akoP603rZbU0EFdxbhZ-djxF7FIVwyKaLnBYU
      - ISSUER_URL=https://authorization.cloudentity.com:8443/default/system
      - ROOT_CA=/ca.pem

  acp:
    container_name: acp
    image: docker.artifactory.syntegrity.com/authorization:aut-1865-openbanking-authorize-integration
    networks:
      system:
        aliases:
          - authorization.cloudentity.com
    ports:
     - 8443:8443
    restart: on-failure
    volumes:
      - ./data/seed.yaml:/seed.yaml
    environment:
      - LOGGING_LEVEL=debug
    command:
     - server
     - start
     - --sql.url
     - postgres://user:password@postgres/authorization?sslmode=disable
     - --hazelcast.address
     - hazelcast:5701
     - --secret.key
     - KNEcLGdDqpwrXDubqPgDSUkMMsLPXaHh
     - --server.cert.path
     - /certs/srv/cert.pem
     - --server.key.path
     - /certs/srv/cert-key.pem
     - --demo
     - --dev

  postgres:
    image: postgres:12.4
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - system
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=authorization

  hazelcast:
    container_name: hazelcast
    image: hazelcast/hazelcast:3.12
    networks:
      - system
    ports:
      - 5701:5701
